### ISSUE TITLE
Backslashes should be escaped in YAML strings.

### ISSUE THREAD

**Issue by jeberger** [js-reporters/js-reporters#114] opened 2019-11-20 11:17 UTC
If an error message contains backslashes, YAML output looks like this:

```yaml
  ---
  message: "Test failed\"
  severity: failed
  ...
```

which is not valid since the backslash now looks like it's escaping the closing double quote. Instead it should be:

```yaml
  ---
  message: "Test failed\\"
  severity: failed
  ...
```

**Comment by Krinkle** [comment] 2020-07-30 16:30
I believe this is a duplicate of https://github.com/js-reporters/js-reporters/issues/109 which was fixed in 1.2.2. Let me know if you still find an issue.

**Closed by Krinkle** 2020-07-30 16:30 UTC
Labels: declined
